---
title: "data manipulation"
author: "Xiaoyue Ma"
date: "5/3/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## import data sets

```{r}
litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## Selecting !!

```{r}
select(litters_data, group, litter_number)
select(litters_data, group, litter_number, starts_with("pups"))
select(litters_data, litter_number, group, everything() )
select(litters_data, -group)
select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP = group, litter_number)

rename(litters_data, GROUP = group)
```


## Filterng!!!

```{r}
filter(litters_data, group == "Con7")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

filter(litters_data, pups_born_alive != 5) 

filter(litters_data, !(pups_born_alive == 5))

filter(litters_data, group %in% c("Con7", "Con8"))

filter(litters_data, group == "Con7", gd_of_birth == 20)

filter(litters_data, group == "Con7" & gd_of_birth == 20)


drop_na(litters_data)
drop_na(litters_data, gd0_weight)
 ```




```{r}

```

## Mutate

```{r}
mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))

```

## Arrange

```{r}
arrange(litters_data, gd_of_birth)
arrange(litters_data, desc(gd_of_birth))
arrange(litters_data, pups_born_alive, gd0_weight)
```





















